{{- if eq .Values.mode "server" -}}
  {{- range $index := until (.Values.deploymentCount | int) }}
    {{- $fullname := include "ggbridge.fullname" $ }}
    {{- $proxyFullname := include "ggbridge.proxy.fullname" $ }}
    {{- $indexProxyFullname := printf "%s-%d" $proxyFullname ($index | int) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $indexProxyFullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.proxy.labels" $ | nindent 4 }}
  {{- if or $.Values.commonAnnotations $.Values.proxy.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $.Values.proxy.annotations $.Values.commonAnnotations ) "context" $ ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.proxy.replicaCount }}
  {{- with $.Values.proxy.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ggbridge.selectorLabels" $ | nindent 6 }}
      {{- include "ggbridge.proxy.selectorLabels" $ | nindent 6 }}
      index: {{ $index | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ printf "%s" (include (print $.Template.BasePath "/proxy/configmap.yaml") $) | sha256sum }}
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ggbridge.labels" $ | nindent 8 }}
        {{- include "ggbridge.proxy.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        index: {{ $index | quote }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ggbridge.serviceAccountName" $ }}
      {{- if $.Values.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml (omit $.Values.podSecurityContext "enabled") | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          {{- if $.Values.containerSecurityContext.enabled }}
          securityContext:
            {{- toYaml (omit $.Values.containerSecurityContext "enabled") | nindent 12 }}
          {{- end }}
          image: {{ include "ggbridge.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ['/usr/sbin/nginx']
          args: ['-c', '/etc/nginx/nginx.conf', '-e', '/dev/stderr', '-g', 'daemon off;']
          ports:
            {{- range $key, $value := $.Values.proxy.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: TCP
            {{- end }}
          {{- if $.Values.proxy.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit $.Values.proxy.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: tmp
              mountPath: /var/lib/nginx/tmp
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {{- toYaml $.Values.proxy.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: {{ $indexProxyFullname }}
            defaultMode: 420
      {{- with $.Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $affinity := include "ggbridge.tplvalues.merge" ( dict "values" ( list $.Values.proxy.affinity (include "ggbridge.proxy.affinity" (dict "index" $index "context" $)) ) "context" $ ) }}
      affinity:
        {{- include "ggbridge.tplvalues.render" ( dict "value" $affinity "context" $) | nindent 8 }}
      {{- with $.Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.proxy.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}


  {{- end }}
{{- end }}
