{{- $gateway := .Values.proxy.tunnels.tls.gateway -}}
{{- if $gateway.enabled -}}
  {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
  {{- if $gateway.gateway.create }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ printf "%s-tls" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations $gateway.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $gateway.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ $gateway.gateway.className | quote }}
  listeners:
    {{- range $gateway.gateway.listeners }}
    - allowedRoutes:
        namespaces:
          from: Same
        kinds:
          - kind: TLSRoute
      name: {{ .hostname | replace "." "-" | trunc 63 | trimSuffix "-" }}
      hostname: {{ .hostname }}
      port: {{ $gateway.gateway.ports.tls }}
      protocol: TLS
      tls:
        mode: Passthrough
    {{- end }}
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ printf "%s-tls" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations $gateway.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $gateway.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  {{- if $gateway.gateway.create }}
  parentRefs:
    - name: {{ printf "%s-tls" $proxyFullname }}
      namespace: {{ .Release.Namespace }}
  {{- else }}
  parentRefs: {{ toYaml $gateway.parentRefs | nindent 4 }}
  {{- end }}
  {{- if $gateway.gateway.listeners -}}
  hostnames:
    {{- range $gateway.gateway.listeners }}
    - {{ .hostname }}
    {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ printf "%s-tls" $proxyFullname }}
          port: {{ .Values.proxy.tunnels.tls.service.ports.tls.port }}
{{- end }}
