{{- $gateway := .Values.proxy.tunnels.web.gateway -}}
{{- if $gateway.enabled -}}
  {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
  {{- if $gateway.gateway.create }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ printf "%s-web" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations $gateway.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $gateway.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ $gateway.gateway.className | quote }}
  listeners:
    {{- range $gateway.gateway.listeners }}
      {{- $tlsEnabled := eq (include "ggbridge.proxy.listener.tlsEnabled" (dict "listener" . "context" $)) "true" }}
    - allowedRoutes:
        namespaces:
          from: Same
        kinds:
          - kind: HTTPRoute
      name: {{ .hostname | replace "." "-" | trunc 63 | trimSuffix "-" }}
      hostname: {{ .hostname }}
      port: {{ ternary $gateway.gateway.ports.https $gateway.gateway.ports.http $tlsEnabled }}
      protocol: {{ ternary "HTTPS" "HTTP" $tlsEnabled }}
      {{- if $tlsEnabled }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .tls.secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-web" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations $gateway.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $gateway.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  {{- if $gateway.gateway.create }}
  parentRefs:
    - name: {{ printf "%s-web" $proxyFullname }}
      namespace: {{ .Release.Namespace }}
  {{- else }}
  parentRefs: {{ toYaml $gateway.parentRefs | nindent 4 }}
  {{- end }}
  {{- if $gateway.gateway.listeners }}
  hostnames:
    {{- range $gateway.gateway.listeners }}
    - {{ .hostname }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ printf "%s-web" $proxyFullname }}
          port: {{ .Values.proxy.tunnels.web.service.ports.web.port }}
{{- end }}
