version: 2
updates:
  # Workflows updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - '*'
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(actions)"
      include: "scope"

  # Composite action in .github/actions/apko/
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/apko"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"

  # Composite action in .github/actions/melange/
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/melange"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"