package:
  name: ggbridge
  version: "1.0.0"
  epoch: 0
  description: Connect your private VCS with GitGuardian
  url: https://github.com/GitGuardian/ggbridge
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nginx-mod-stream
      - wstunnel
      - openresty
  target-architecture:
    - aarch64
    - x86_64
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wget
  environment:
    CGO_ENABLED: "0"
pipeline:
  - uses: go/build
    with:
      packages: .
      ldflags: |
        -X main.version=${{package.version}}
      output: ggbridge
      tags: gitguardian
  - runs: |
      install -dm755 "${{targets.destdir}}"/opt/ggbridge
      install -dm755 "${{targets.destdir}}"/etc/ggbridge
      install -dm755 "${{targets.destdir}}"/etc/ggbridge/ssl
      install -dm775 "${{targets.destdir}}"/etc/ggbridge/ssl/certs
      install -dm775 "${{targets.destdir}}"/etc/ggbridge/ssl/private
      install -dm755 "${{targets.destdir}}"/etc/ggbridge/tls

      install -dm777 "${{targets.destdir}}"/var/run/openresty
      install -dm777 "${{targets.destdir}}"/var/run/openresty/nginx-client-body
      install -dm777 "${{targets.destdir}}"/var/cache/openresty
      install -dm777 "${{targets.destdir}}"/var/log/openresty

      install -m755 docker/scripts/run.sh "${{targets.destdir}}"/opt/ggbridge/run.sh
      install -m644 docker/nginx/nginx.conf "${{targets.destdir}}"/etc/ggbridge/nginx.conf
  - uses: strip
