package:
  name: wstunnel
  version: "10.1.9"
  epoch: 0
  description: Wstunnel uses the websocket protocol which is compatible with http in order to bypass firewalls and proxies
  url: https://github.com/erebe/wstunnel
  copyright:
    - license: BSD-3-Clause
  target-architecture:
    - aarch64
    - x86_64
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
pipeline:
  - if: ${{build.arch}} == 'aarch64'
    uses: fetch
    with:
      uri: https://github.com/erebe/wstunnel/releases/download/v${{package.version}}/wstunnel_${{package.version}}_linux_arm64.tar.gz
      expected-sha256: 77e256ccef8ab02d21752207fbdb8f27587cf53eafa98f7e878db8979a8a130f
      strip-components: 0
  - if: ${{build.arch}} == 'x86_64'
    uses: fetch
    with:
      uri: https://github.com/erebe/wstunnel/releases/download/v${{package.version}}/wstunnel_${{package.version}}_linux_amd64.tar.gz
      expected-sha256: d4c6178e7e7756a49386ba6f419345da4b8b53996390100cfafb2323fc853fbb
      strip-components: 0
  - runs: |
      install -dm755 "${{targets.destdir}}"/usr/bin
      install -dm755 "${{targets.destdir}}"/etc/wstunnel
      install -m755 ${{package.name}} "${{targets.destdir}}"/usr/bin/${{package.name}}
