default_stages: [pre-commit]
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.29
    hooks:
      - id: gofmt
      - id: golangci-lint
      - id: helmlint
        files: ^helm/ggbridge/
  - repo: https://github.com/norwoodj/helm-docs
    rev:  v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=helm/ggbridge
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.40.0
    hooks:
      - id: ggshield
        language_version: python3
