{{- if .Values.server.tls.certManager.enabled -}}
  {{- $fullname := include "ggbridge.fullname" . -}}
  {{- $namespace := ternary (default .Release.namespace .Values.server.istio.gateway.namespace) .Release.namespace .Values.server.istio.enabled -}}
  {{- if eq .Values.server.tls.certManager.issuer.name "selfSigned" }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-selfsigned" $fullname }}
  namespace: {{ $namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-ca" $fullname }}
  namespace: {{ $namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  isCA: true
  commonName: {{ printf "%s-ca" $fullname }}
  secretName: {{ printf "%s-ca" $fullname }}
  duration: 87600h # 10 years
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ printf "%s-selfsigned" $fullname }}
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-ca" $fullname }}
  namespace: {{ $namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ca:
    secretName: {{ printf "%s-ca" $fullname }}
  {{- end }}
{{- end }}
