{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ggbridge.serviceAccountName" . }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.serviceAccount.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list .Values.serviceAccount.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
  name: {{ include "ggbridge.fullname" . }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'configmpas'
      - 'secrets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ggbridge.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ggbridge.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ggbridge.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
