---
{{- $openShiftRoute := .Values.proxy.tunnels.web.openShiftRoute -}}
{{- if $openShiftRoute.enabled -}}
  {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
  {{- range $openShiftRoute.listeners }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ printf "%s-web-%s" $proxyFullname (.hostname | replace "." "-") | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.proxy.labels" $ | nindent 4 }}
  {{- if or $.Values.commonAnnotations $openShiftRoute.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $openShiftRoute.annotations $.Values.commonAnnotations ) "context" $ ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  host: {{ .hostname }}
  path: /
  to:
    kind: Service
    name: {{ printf "%s-web" $proxyFullname }}
    weight: 100
  port:
    targetPort: web
  tls: {{- toYaml .tls | nindent 4 }}
  {{- end }}
{{- end }}
