{{- if and (eq .Values.mode "server") .Values.tls.certManager.enabled -}}
  {{- $fullname := include "ggbridge.fullname" . -}}
  {{- $serverFullname := include "ggbridge.server.fullname" . }}
  {{- $namespace := ternary (default .Release.namespace .Values.server.istio.gateway.namespace) .Release.namespace .Values.server.istio.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-crt" $serverFullname }}
  namespace: {{ $namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.server.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ printf "%s-crt" $serverFullname }}
  duration: 17520h # 2 years
  privateKey:
    algorithm: RSA
    size: 2048
  commonName: {{ include "ggbridge.hostname" . }}
  dnsNames:
    - {{ include "ggbridge.hostname" . }}
  usages:
    - server auth
  issuerRef:
    {{- if .Values.tls.certManager.spec }}
    name: {{ printf "%s-ca" $fullname }}
    {{- else }}
    name: {{ .Values.tls.certManager.issuer.name }}
    {{- end }}
    kind: {{ .Values.tls.certManager.issuer.kind }}
{{- end }}
