{{- if (eq .Values.mode "server") -}}
  {{- $serverFullname := include "ggbridge.server.fullname" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serverFullname }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  nginx.conf: |-
    {{ tpl (.Files.Get "files/nginx.conf") . | nindent 4 }}
{{- end }}
