{{- if and (eq .Values.mode "server") .Values.server.istio.enabled }}
  {{- $serverFullname := include "ggbridge.server.fullname" . }}

{{- if .Values.server.istio.gateway.create }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $serverFullname }}
  namespace: {{ default .Release.Namespace .Values.server.istio.gateway.namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.server.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.server.istio.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list .Values.server.istio.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  selector: {{ toYaml .Values.server.istio.gateway.selector | nindent 4 }}
  servers:
    {{- if .Values.tls.enabled }}
    - port:
        number: {{ .Values.server.istio.gateway.ports.https }}
        name: https
        protocol: HTTPS
      tls:
        mode: {{ upper .Values.tls.mode }}
        minProtocolVersion: {{ .Values.server.istio.gateway.tls.minProtocolVersion }}
        {{- if ne .Values.tls.mode "passthrough" }}
          {{- if .Values.tls.existingSecret }}
        credentialName: {{ .Values.tls.existingSecret }}
          {{- else }}
        credentialName: {{ printf "%s-crt" $serverFullname }}
          {{- end }}
        {{- end }}
    {{- else }}
    - port:
        number: {{ .Values.server.istio.gateway.ports.http }}
        name: http
        protocol: HTTP
    {{- end }}
      hosts:
        - {{ include "ggbridge.hostname" . | quote }}
{{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $serverFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.server.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.server.istio.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list .Values.server.istio.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - {{ include "ggbridge.hostname" $ | quote }}
  {{- if .Values.server.istio.gateway.create }}
  gateways:
    - {{ printf "%s/%s" (default .Release.Namespace .Values.server.istio.gateway.namespace) $serverFullname }}
  {{- else }}
  gateways: {{ toYaml .Values.server.istio.gateways | nindent 4 }}
  {{- end }}
  tls:
    - match:
        - port: {{ $.Values.server.istio.gateway.ports.https }}
          sniHosts:
            - {{ include "ggbridge.hostname" $ | quote }}
      route:
        - destination:
            host: {{ $serverFullname }}
            port:
              number: {{ $.Values.server.service.ports.ws.port }}
  http:
    {{- range $index := until ($.Values.deploymentCount | int) }}
      {{- $serverFullname := include "ggbridge.server.fullname" $ }}
      {{- $indexServerFullname := printf "%s-%d" $serverFullname ($index | int) }}
    - match:
        - uri:
            prefix: {{ printf "/%d" ($index | int) }}
      route:
        - destination:
            host: {{ $indexServerFullname }}
            port:
              number: {{ $.Values.server.service.ports.ws.port }}
    {{- end }}
    - route:
        - destination:
            host: {{ $serverFullname }}
            port:
              number: {{ $.Values.server.service.ports.ws.port }}

{{- end }}
