{{- if and (eq .Values.mode "server") (include "ggbridge.hostname" .) -}}
  {{- $fullname := include "ggbridge.fullname" $ }}
  {{- $serverFullname := include "ggbridge.server.fullname" $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serverFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.server.labels" . | nindent 4 }}
  {{- with (include "ggbridge.server.service.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.ws.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "ggbridge.selectorLabels" . | nindent 4 }}
    {{- include "ggbridge.server.selectorLabels" . | nindent 4 }}

  {{- range $index := until (include "ggbridge.deploymentCount" . | int) }}
    {{- $indexServerFullname := printf "%s-%d" $serverFullname ($index | int) }}
    {{- $indexServerProxyFullname := printf "%s-proxy-%d" $serverFullname ($index | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $indexServerFullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.server.labels" $ | nindent 4 }}
  {{- with (include "ggbridge.server.service.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.ports.ws.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "ggbridge.selectorLabels" $ | nindent 4 }}
    {{- include "ggbridge.server.selectorLabels" $ | nindent 4 }}
    index: {{ $index | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $indexServerProxyFullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.server.labels" $ | nindent 4 }}
  {{- if or $.Values.commonAnnotations $.Values.service.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $.Values.service.annotations $.Values.commonAnnotations ) "context" $ ) }}
  annotations: {{- include "ggbridge.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.proxy.service.type }}
  ports:
    - port: {{ $.Values.proxy.service.ports.socks.port }}
      targetPort: socks
      protocol: TCP
      name: socks
  selector:
    {{- include "ggbridge.selectorLabels" $ | nindent 4 }}
    {{- include "ggbridge.server.selectorLabels" $ | nindent 4 }}
    index: {{ $index | quote }}

  {{- end }}
{{- end }}
