name: Publish Docker images
description: 'Publish Docker images using APKO'

inputs:
  config:
    description: 'The APKO config file'
    required: true
  tag:
    description: 'The image tag'
    required: true
  arch:
    description: 'The architecture to build for'
    required: false
    default: ''
  keyring-append:
    description: 'Extra key to include in the keyring'
    required: false
    default: ''
  repository-append:
    description: 'Extra repository to include'
    required: false
    default: ''
  dockerhub-username:
    description: 'Username for Docker Hub authentication'
    required: true
  dockerhub-token:
    description: 'Password for Docker Hub authentication'
    required: true
  sbom-path:
    description: 'The SBOM directory'
    required: false
    default: ${{ runner.temp }}/sbom
  dagger-version:
    description: 'The Dagger Engine version'
    required: false
    default: 'latest'
  dagger-cloud-token:
    description: 'The Dagger cloud token'
    required: false
    default: ''

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.digest.outputs.output }}

runs:
  using: composite
  steps:
    - name: Publish image
      id: publish
      uses: dagger/dagger-for-github@8.0.0
      env:
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
        GH_TOKEN: ${{ github.token }}
      with:
        engine-stop: false
        version: ${{ inputs.dagger-version }}
        cloud-token: ${{ inputs.dagger-cloud-token }}
        module: github.com/opopops/daggerverse/apko@v1.7.1
        verb: call
        args: |
          with-registry-auth \
            --address=ghcr.io \
            --username=${{ github.actor }} \
            --secret=env:GH_TOKEN \
          with-registry-auth \
            --address=docker.io \
            --username=${{ inputs.dockerhub-username }} \
            --secret=env:DOCKERHUB_TOKEN \
          publish \
            --context=${{ github.workspace }} \
            --config=${{ inputs.config }} \
            --tag=ghcr.io/${{ inputs.tag }} \
            --tag=docker.io/${{ inputs.tag }} \
            --arch=${{ inputs.arch }} \
            --keyring-append=${{ inputs.keyring-append }} \
            --repository-append=${{ inputs.repository-append }} \
          sbom-dir \
          export --path ${{ inputs.sbom-path }} \

    - name: Digest
      id: digest
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: ${{ inputs.dagger-version }}
        cloud-token: ${{ inputs.dagger-cloud-token }}
        module: github.com/opopops/daggerverse/crane@v1.3.0
        verb: call
        args: |
          digest \
            --image=ghcr.io/${{ inputs.tag }} \
