name: Publish Docker images
description: 'Publish Docker images using APKO'

inputs:
  config:
    description: 'The APKO config file'
    required: true
  tag:
    description: 'The image tag'
    required: true
  arch:
    description: 'The architecture to build for'
    required: false
    default: ''
  key:
    description: 'Extra key to include in the keyring'
    required: false
    default: ''
  repository:
    description: 'Extra repository to include'
    required: false
    default: ''
  dockerhub-username:
    description: 'Username for Docker Hub authentication'
    required: true
  dockerhub-password:
    description: 'Password for Docker Hub authentication'
    required: true

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.publish.outputs.output }}

runs:
  using: composite
  steps:
    - name: Publish image
      id: publish
      uses: dagger/dagger-for-github@v7
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        engine-stop: false
        module: github.com/opopops/daggerverse/apko@v1.5.4
        verb: call
        args: |
          with-registry-auth \
            --address=ghcr.io \
            --username=${{ github.actor }} \
            --secret=env:GH_TOKEN \
          publish \
            --context=${{ github.workspace }} \
            --config=${{ inputs.config }} \
            --tag=ghcr.io/${{ inputs.tag }} \
            --arch=${{ inputs.arch }} \
            --keyring-append=${{ inputs.key }} \
            --repository-append=${{ inputs.repository }} \
          digest \

    - name: Copy image to Docker Hub
      uses: dagger/dagger-for-github@v7
      env:
        DOCKER_HUB_PASSWORD: ${{ inputs.dockerhub-password }}
        GH_TOKEN: ${{ github.token }}
      with:
        module: github.com/opopops/daggerverse/crane@v1.2.2
        verb: call
        args: |
          with-registry-auth \
            --address=ghcr.io \
            --username=${{ github.actor }} \
            --secret=env:GH_TOKEN \
          with-registry-auth \
            --address=docker.io \
            --username=${{ inputs.dockerhub-username }} \
            --secret=env:DOCKER_HUB_PASSWORD \
          copy \
            --source=ghcr.io/${{ inputs.tag }} \
            --target=docker.io/${{ inputs.tag }} \
