name: Publish Helm chart
description: 'Publish Helm chart'

inputs:
  version:
    description: 'The Helm chart version'
    required: true
  app-version:
    description: 'The Helm chart App version'
    required: true

runs:
  using: composite
  steps:
    - name: Lint Helm chart
      uses: dagger/dagger-for-github@v7
      with:
        engine-stop: false
        module: github.com/opopops/daggerverse/helm@v1.2.2
        verb: call
        args: |
          lint \
            --path=helm/ggbridge \
            --strict \

    - name: Publish Helm chart
      uses: dagger/dagger-for-github@v7
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        module: github.com/opopops/daggerverse/helm@v1.2.2
        verb: call
        args: |
          package-push \
            --path=helm/ggbridge \
            --version="${{ inputs.version }}" \
            --app-version="${{ inputs.app-version }}" \
            --registry=ghcr.io/gitguardian/ggbridge/helm \
            --username=${{ github.actor }} \
            --password=env:GH_TOKEN \
