name: Publish Helm chart
description: 'Publish Helm chart'

inputs:
  registry:
    description: 'The Helm registry'
    required: true
  version:
    description: 'The Helm chart version'
    required: true
  app-version:
    description: 'The Helm chart App version'
    required: true
  dagger-version:
    description: 'The Dagger Engine version'
    required: false
    default: 'latest'
  dagger-cloud-token:
    description: 'The Dagger cloud token'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Publish Helm chart
      uses: dagger/dagger-for-github@v7
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        version: ${{ inputs.dagger-version }}
        cloud-token: ${{ inputs.dagger-cloud-token }}
        module: github.com/opopops/daggerverse/helm@v1.2.3
        verb: call
        args: |
          package-push \
            --path=helm/ggbridge \
            --version="${{ inputs.version }}" \
            --app-version="${{ inputs.app-version }}" \
            --registry=${{ inputs.registry }} \
            --username=${{ github.actor }} \
            --password=env:GH_TOKEN \
