name: Keygen
description: 'Generate a key for package signin'

inputs:
  output-dir:
    description: 'Output dir'
    required: false
    default: ${{ runner.temp }}/packages
  dagger-version:
    description: 'The Dagger Engine version'
    required: false
    default: 'latest'
  dagger-cloud-token:
    description: 'The Dagger cloud token'
    required: false
    default: ''

outputs:
  signing-key:
    description: 'Signing key'
    value: ${{ steps.output.outputs.signing-key }}
  public-key:
    description: 'Public key'
    value: ${{ steps.output.outputs.public-key }}

runs:
  using: composite
  steps:
    - name: Create outputs
      id: output
      shell: bash
      run: |
        OUTPUT_DIR="${{ inputs.output-dir }}"
        mkdir -p "$OUTPUT_DIR"
        echo "signing-key=${OUTPUT_DIR}/melange.rsa" >> $GITHUB_OUTPUT
        echo "public-key=${OUTPUT_DIR}/melange.rsa.pub" >> $GITHUB_OUTPUT

    - name: Keygen
      uses: dagger/dagger-for-github@8.0.0
      with:
        version: ${{ inputs.dagger-version }}
        cloud-token: ${{ inputs.dagger-cloud-token }}
        module: github.com/opopops/daggerverse/melange@v1.5.0
        verb: call
        args: |
          keygen \
          export \
            --path=${{ inputs.output-dir }} \
