{{- if and (include "ggbridge.client.hostname" .) .Values.client.networkPolicy.enabled }}
{{- $clientFullname := include "ggbridge.client.fullname" . }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $clientFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.client.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "ggbridge.selectorLabels" . | nindent 6 }}
      {{- include "ggbridge.client.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - ports:
         # Allow dns resolution
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        {{- if .Values.client.tls.enabled }}
        - port: 443
          protocol: TCP
        {{- else }}
        - port: 80
          protocol: TCP
        {{- end }}
    {{- if .Values.client.networkPolicy.extraEgress }}
    {{- include "ggbridge.tplvalues.render" ( dict "value" .Values.client.networkPolicy.extraEgress "context" . ) | nindent 4 }}
    {{- end }}
  ingress: []
{{- end }}
