name: Tag Docker image
description: 'Tag a Docker image using Crane'

inputs:
  image:
    description: 'The Docker image to tag'
    required: true
  tag:
    description: 'The tag to add'
    required: true
  dockerhub-username:
    description: 'Username for Docker Hub authentication'
    required: true
  dockerhub-token:
    description: 'Password for Docker Hub authentication'
    required: true
  dagger-version:
    description: 'The Dagger Engine version'
    required: false
    default: 'latest'
  dagger-cloud-token:
    description: 'The Dagger cloud token'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Add tag
      uses: dagger/dagger-for-github@8.0.0
      env:
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
        GH_TOKEN: ${{ github.token }}
      with:
        version: ${{ inputs.dagger-version }}
        cloud-token: ${{ inputs.dagger-cloud-token }}
        module: github.com/opopops/daggerverse/crane@v1.4.0
        verb: call
        args: |
          with-registry-auth \
            --address=ghcr.io \
            --username=${{ github.actor }} \
            --secret=env:GH_TOKEN \
          with-registry-auth \
            --address=docker.io \
            --username=${{ inputs.dockerhub-username }} \
            --secret=env:DOCKERHUB_TOKEN \
          with-tag \
            --image=ghcr.io/${{ inputs.image }} \
            --tag=${{ inputs.tag }} \
          tag \
            --image=docker.io/${{ inputs.image }} \
            --tag=${{ inputs.tag }} \
