{{- if (eq .Values.mode "server") -}}
  {{- range $index := until (.Values.deploymentCount | int) }}
    {{- $fullname := include "ggbridge.fullname" $ }}
    {{- $serverFullname := include "ggbridge.server.fullname" $ }}
    {{- $indexServerFullname := printf "%s-%d" $serverFullname ($index | int) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $indexServerFullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.server.labels" $ | nindent 4 }}
    index: {{ $index | quote }}
  {{- if or $.Values.commonAnnotations $.Values.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $.Values.annotations $.Values.commonAnnotations ) "context" $ ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.replicaCount }}
  {{- with $.Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ggbridge.selectorLabels" $ | nindent 6 }}
      {{- include "ggbridge.server.selectorLabels" $ | nindent 6 }}
      index: {{ $index | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ printf "%s" (include (print $.Template.BasePath "/server/configmap.yaml") $) | sha256sum }}
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ggbridge.labels" $ | nindent 8 }}
        {{- include "ggbridge.server.labels" $ | nindent 8 }}
        index: {{ $index | quote }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ggbridge.serviceAccountName" $ }}
      {{- if $.Values.podSecurityContext.enabled }}
      securityContext:
        {{- toYaml (omit $.Values.podSecurityContext "enabled") | nindent 8 }}
      {{- end }}
      {{- if or $.Values.caBundle.certs $.Values.caBundle.existingSecret }}
      initContainers:
        - name: ca
          {{- if $.Values.containerSecurityContext.enabled }}
          securityContext:
            {{- toYaml (omit $.Values.containerSecurityContext "enabled") | nindent 12 }}
          {{- end }}
          image: {{ include "ggbridge.shell.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -x
              cat $SSL_CERT_FILE > /certs/ca-bundle.crt
              if [ -s /ca-bundle/ca-bundle.crt ]; then
                cat /ca-bundle/ca-bundle.crt  >> /certs/ca-bundle.crt
              fi
              chmod 0444 /certs/ca-bundle.crt
          volumeMounts:
            - name: ca-certs
              mountPath: /certs
            - name: ca-bundle
              mountPath: /ca-bundle
              readOnly: true
      {{- end }}
      containers:
        - name: ggbridge
          {{- if $.Values.containerSecurityContext.enabled }}
          securityContext:
            {{- toYaml (omit $.Values.containerSecurityContext "enabled") | nindent 12 }}
          {{- end }}
          image: {{ include "ggbridge.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["ggbridge"]
          args: ["server"]
          env:
            - name: SERVER_LISTEN
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: {{$.Values.server.service.ports.ws.containerPort | quote }}
            {{- if and $.Values.tls.enabled (eq (include "ggbridge.server.trafficRouting.enabled" $) "false") }}
            - name: TLS_ENABLED
              value: "true"
            {{- end }}
            {{- with $.Values.logLevel }}
            - name: LOG_LEVEL
              value: {{ . | quote }}
            {{- end }}
            - name: NGINX_EMBEDDED
              value: "false"
            - name: TUNNEL_HEALTH_PORT
              value: {{ $.Values.proxy.service.ports.health.containerPort | quote }}
            - name: TUNNEL_HEALTH_REMOTE_PORT
              value: {{ $.Values.proxy.service.ports.health.remoteContainerPort | quote }}
            - name: TUNNEL_SOCKS_PORT
              value: {{ $.Values.proxy.service.ports.socks.containerPort | quote }}
            - name: TUNNEL_TLS_PORT
              value: {{ $.Values.proxy.service.ports.tls.containerPort | quote }}
            - name: TUNNEL_TLS_REMOTE_PORT
              value: {{ $.Values.proxy.service.ports.tls.remoteContainerPort | quote }}
            - name: TUNNEL_WEB_PORT
              value: {{ $.Values.proxy.service.ports.web.internalPort | quote }}
            - name: TUNNEL_WEB_REMOTE_PORT
              value: {{ $.Values.proxy.service.ports.web.remoteContainerPort | quote }}
            - name: RESTRICT_CONFIG
              value: /etc/ggbridge/restrictions.yaml
            {{- if or $.Values.caBundle.certs $.Values.caBundle.existingSecret }}
            - name: SSL_CERT_FILE
              value: /certs/ca-bundle.crt
            {{- end }}
            {{- if $.Values.extraEnv }}
            {{- include "ggbridge.tplvalues.render" (dict "value" $.Values.extraEnv "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - name: ws
              containerPort: {{ $.Values.server.service.ports.ws.containerPort }}
              protocol: TCP
            {{- range $key, $value := $.Values.client.reverseTunnels }}
              {{- if $value.enabled }}
                {{- $port := get $.Values.proxy.service.ports $key }}
            - name: {{ $key }}
              containerPort: {{ $port.containerPort }}
              protocol: TCP
              {{- end }}
            {{- end }}
          volumeMounts:
            - name: run
              mountPath: /var/run
            - name: ca-certs
              mountPath: /certs
              readOnly: true
            - name: config
              mountPath: /etc/ggbridge/restrictions.yaml
              subPath: restrictions.yaml
              readOnly: true
            {{- if and $.Values.tls.enabled (eq (include "ggbridge.server.trafficRouting.enabled" $) "false") }}
            - name: tls-secret
              mountPath: /etc/ggbridge/tls
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
        - name: nginx
          {{- if $.Values.containerSecurityContext.enabled }}
          securityContext:
            {{- toYaml (omit $.Values.containerSecurityContext "enabled") | nindent 12 }}
          {{- end }}
          image: {{ include "ggbridge.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ['/usr/sbin/nginx']
          args: ['-c', '/etc/nginx/nginx.conf', '-e', '/dev/stderr', '-g', 'daemon off;']
          {{- if or $.Values.caBundle.certs $.Values.caBundle.existingSecret }}
          env:
            - name: SSL_CERT_FILE
              value: /certs/ca-bundle.crt
          {{- end }}
          volumeMounts:
            - name: ca-certs
              mountPath: /certs
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-tmp
              mountPath: /var/lib/nginx/tmp
            - name: run
              mountPath: /var/run
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: ca-certs
          emptyDir: {}
        {{- if or $.Values.caBundle.certs $.Values.caBundle.existingSecret }}
        - name: ca-bundle
          secret:
            {{- if $.Values.caBundle.certs }}
            secretName: {{ printf "%s-ca-bundle" $fullname }}
            items:
              - key: ca.crt
                path: ca-bundle.crt
            {{- else }}
            secretName: {{ $.Values.caBundle.existingSecret }}
            items:
              - key: {{ default "ca.crt" $.Values.tls.existingSecretKeys.caCrt }}
                path: ca-bundle.crt
            {{- end }}
        {{- end }}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: config
          configMap:
            name: {{ $serverFullname }}
            defaultMode: 420
      {{- if and $.Values.tls.enabled (eq (include "ggbridge.server.trafficRouting.enabled" $) "false") }}
        - name: tls-secret
          secret:
            {{- if $.Values.tls.existingSecret }}
            secretName: {{ $.Values.tls.existingSecret }}
            items:
              {{- with $.Values.tls.existingSecretKeys.caCrt }}
              - key: {{ . }}
                path: ca.crt
              {{- end }}
              - key: {{ default "tls.crt" $.Values.tls.existingSecretKeys.crt }}
                path: server.crt
              - key: {{ default "tls.key" $.Values.tls.existingSecretKeys.key }}
                path: server.key
            {{- else}}
            secretName: {{ printf "%s-crt" $serverFullname }}
            items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
            {{- end }}
            defaultMode: 420
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $affinity := include "ggbridge.tplvalues.merge" ( dict "values" ( list $.Values.affinity (include "ggbridge.affinity" (dict "index" $index "context" $)) ) "context" $ ) }}
      affinity:
        {{- include "ggbridge.tplvalues.render" ( dict "value" $affinity "context" $) | nindent 8 }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- end }}
{{- end }}
