{{- if and (eq .Values.mode "server") .Values.server.gateway.enabled }}
  {{- $serverFullname := include "ggbridge.server.fullname" . }}
  {{- if .Values.server.gateway.gateway.create }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $serverFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.server.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.server.gateway.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list .Values.server.gateway.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.server.gateway.gateway.className | quote }}
  listeners:
    - hostname: {{ include "ggbridge.hostname" . }}
      allowedRoutes:
        namespaces:
          from: Same
      {{- if .Values.tls.enabled }}
      name: https
      port: {{ .Values.server.gateway.gateway.ports.https }}
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
          {{- if .Values.tls.existingSecret }}
            name: {{ .Values.tls.existingSecret }}
          {{- else }}
            name: {{ printf "%s-crt" $serverFullname }}
          {{- end }}
        {{- if (eq (lower .Values.tls.mode) "mutual") }}
        options:
          clientCertificateRef:
            kind: Secret
            group: ""
            {{- if .Values.tls.existingSecret }}
            name: {{ .Values.tls.existingSecret }}
            {{- else }}
            name: {{ printf "%s-crt" $serverFullname }}
            {{- end }}
        {{- end }}
      {{- else }}
      name: http
      port: {{ .Values.server.gateway.gateway.ports.http }}
      protocol: HTTP
      {{- end }}
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $serverFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.server.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.server.gateway.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list .Values.server.gateway.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.gateway.gateway.create }}
  parentRefs:
    - name: {{ $serverFullname }}
      namespace: {{ .Release.Namespace }}
      sectionName: {{ ternary "https" "http" .Values.tls.enabled }}
  {{- else }}
  parentRefs: {{ toYaml .Values.server.gateway.parentRefs | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ include "ggbridge.hostname" . }}
  rules:
    - backendRefs:
        - name: {{ $serverFullname }}
          port: {{ $.Values.server.service.ports.ws.port }}
      matches:
        - path:
            type: PathPrefix
            value: /
        {{- range $index := until ($.Values.deploymentCount | int) }}
          {{- $serverFullname := include "ggbridge.server.fullname" $ }}
          {{- $indexServerFullname := printf "%s-%d" $serverFullname ($index | int) }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ printf "/%d" ($index | int) }}
      backendRefs:
        - name: {{ $indexServerFullname }}
          port: {{ $.Values.server.service.ports.ws.port }}
        {{- end }}
{{- end }}
