name: Sign and Attest Image
description: 'Sign  and Attest Image using Cosign'

inputs:
  image:
    description: 'The image name'
    required: true
  sbom-path:
    description: 'The SBOM directory'
    required: false
    default: ${{ github.workspace }}/sbom
  attest-sbom:
    description: 'Attest SBOMs'
    required: false
    default: 'true'
  attest-provenance:
    description: 'Attest the build provenance'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - id: vars
      shell: bash
      run: |
        echo "image-name=$(echo ${{ inputs.image }} | cut -d':' -f1)" >> $GITHUB_OUTPUT
        echo "image-tag=$(echo ${{ inputs.image }} | cut -d':' -f2)" >> $GITHUB_OUTPUT
        echo "digest=$(crane digest ${{ inputs.image }})" >> $GITHUB_OUTPUT
        echo "digest-amd64=$(crane digest ${{ inputs.image }} --platform=linux/amd64)" >> $GITHUB_OUTPUT
        echo "digest-arm64=$(crane digest ${{ inputs.image }} --platform=linux/arm64)" >> $GITHUB_OUTPUT

    - id: sign
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign sign \
          --recursive \
          --oidc-provider=github-actions \
          ${{ inputs.image }}@${{ steps.vars.outputs.digest }}

    - if: ${{ inputs.attest-sbom == 'true' }}
      id: attest-sbom-index
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-index.spdx.json \
          --oidc-provider=github-actions \
          ${{ inputs.image }}@${{ steps.vars.outputs.digest }}

    - if: ${{ inputs.attest-sbom == 'true' }}
      id: attest-sbom-amd64
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-x86_64.spdx.json \
          --oidc-provider=github-actions \
          ${{ inputs.image }}@${{ steps.vars.outputs.digest-amd64 }}

    - if: ${{ inputs.attest-sbom == 'true' }}
      id: attest-sbom-arm64
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-aarch64.spdx.json \
          --oidc-provider=github-actions \
          ${{ inputs.image }}@${{ steps.vars.outputs.digest-arm64 }}

    - if: ${{ inputs.attest-provenance == 'true' }}
      id: attest-provenance-github
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ steps.vars.outputs.image-name }}
        subject-digest: ${{ steps.vars.outputs.digest }}
        push-to-registry: true
