# Ref: https://k3d.io/stable/usage/configfile/#config-options
# yaml-language-server: $schema=https://raw.githubusercontent.com/k3d-io/k3d/main/pkg/config/v1alpha5/schema.json
---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ggbridge
servers: 1
agents: 0
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6445"
image: rancher/k3s:v1.33.5-k3s1
files:
  - description: 'GGbridge namespace'
    source: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ggbridge
    destination: /var/lib/rancher/k3s/server/manifests/ggbridge-ns.yaml
    nodeFilters:
    - "server:*"
options:
  k3d:
    wait: true
    timeout: 3m0s
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: "--disable=metrics-server"
        nodeFilters:
          - "server:*"
      - arg: "--disable=local-storage"
        nodeFilters:
          - "server:*"
      - arg: "--disable=servicelb"
        nodeFilters:
          - "server:*"
    nodeLabels:
      - label: project=ggbridge
        nodeFilters:
          - server:*
          - agent:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
