{{- $ingress := .Values.proxy.tunnels.tls.ingress -}}
{{- if $ingress.enabled -}}
  {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
  {{- if (eq $ingress.controller "traefik") }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ printf "%s-tls" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations $ingress.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $ingress.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  routes:
    {{- range $ingress.hostnames }}
    - match: {{ printf "HostSNI(`%s`)" . }}
      services:
        - name: {{ printf "%s-tls" $proxyFullname }}
          port: {{ $.Values.proxy.tunnels.tls.service.ports.tls.port }}
    {{- end }}
  tls:
    passthrough: true
  {{- else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-tls" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  annotations: {{ include "ggbridge.proxy.tunnels.tls.ingress.annotations" . | nindent 4 }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className | quote }}
  {{- end }}
  rules:
    {{- range $ingress.listeners }}
    - host: {{ .hosntame }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-tls" $proxyFullname }}
                port:
                  number: {{ .Values.proxy.tunnels.tls.service.ports.tls.port }}
    {{- end }}
  {{- end }}
{{- end }}
