{{- $tunnel :=  ternary .Values.server.tunnels.web .Values.client.tunnels.web (eq .Values.mode "server") -}}
{{- $servicePort :=  .Values.proxy.service.ports.web -}}
{{- if and .Values.proxy.ingress.web.enabled $tunnel.enabled -}}
  {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
  {{- if and (eq .Values.proxy.ingress.tls.controller "traefik") $tunnel.tls.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-web" $proxyFullname }}
spec:
  redirectScheme:
    scheme: https
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-web" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  annotations: {{ include "ggbridge.proxy.ingress.web.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.proxy.ingress.web.className | quote }}
  rules:
    {{- range $tunnel.listeners }}
    - host: {{ .hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ggbridge.proxy.serviceName" $ }}
                port:
                  number: {{ $servicePort.port }}
    {{- end }}
  {{- if $tunnel.tls.enabled }}
  tls:
    {{- range $tunnel.listeners }}
    - hosts:
      - {{ .hostname }}
      secretName: {{ .tls.secretName }}
    {{- end }}
  {{- end }}
{{- end }}
