{{- $ingress := .Values.proxy.tunnels.web.ingress -}}
{{- if $ingress.enabled -}}
  {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
  {{- if and (eq $ingress.controller "traefik") $ingress.tls.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-web" $proxyFullname }}
spec:
  redirectScheme:
    scheme: https
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-web" $proxyFullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  annotations: {{ include "ggbridge.proxy.tunnels.web.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ $ingress.className | quote }}
  rules:
    {{- range $ingress.listeners }}
    - host: {{ .hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-web" $proxyFullname }}
                port:
                  number: {{ .Values.proxy.tunnels.web.service.ports.web.port }}
    {{- end }}
  {{- if $ingress.tls.enabled }}
  tls:
    {{- range $ingress.listeners }}
    - hosts:
      - {{ .hostname }}
      secretName: {{ .tls.secretName }}
    {{- end }}
  {{- end }}
{{- end }}
