# Deploy ggbridge server and specify certManager issuer to generate server certificates

mode: server
domain: gitguardian.com
subdomain: my-subdomain

tls:
  enabled: true
  certManager:
    enabled: true
    issuer:
      name: ggbridge-issuer
      kind: Issuer

ingress:
  enabled: true
  controller: nginx
  className: nginx
