# Deploy ggbridge server and specify certManager issuer to generate server certificates
domain: gitguardian.com

server:
  subdomain: my-subdomain

  tls:
    enabled: true
    certManager:
      enabled: true
      issuer:
        name: ggbridge-issuer
        kind: Issuer

  ingress:
    enabled: true
    controller: nginx
    className: nginx
