{{- if (eq (include "ggbridge.proxy.enabled" .) "true") -}}
  {{- $ports := include "ggbridge.proxy.service.ports" . | fromYaml -}}
  {{- if $ports -}}
    {{- $proxyFullname := include "ggbridge.proxy.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ggbridge.proxy.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" . | nindent 4 }}
    {{- include "ggbridge.proxy.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.proxy.service.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list .Values.proxy.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "ggbridge.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    {{- include "ggbridge.proxy.service.ports" . | nindent 4 }}
  selector:
    {{- include "ggbridge.selectorLabels" . | nindent 4 }}
    {{- if and (eq .Values.mode "server") (gt (.Values.proxy.replicaCount | int) 0) }}
    {{- include "ggbridge.proxy.selectorLabels" . | nindent 4 }}
    {{- else }}
      {{- if eq .Values.mode "server" }}
        {{- include "ggbridge.server.selectorLabels" . | nindent 4 }}
      {{- else }}
        {{- include "ggbridge.client.selectorLabels" . | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
