---
hostname: <id>.ggbridge.gitguardian.com

tls:
  enabled: true
  existingSecret: ggbridge-client-crt
  existingSecretKeys:
    caCrt: ca.crt
    crt: tls.crt
    key: tls.key

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

client:
  tunnels:
    tls:
      enabled: true

proxy:
  resolver: dns-default.openshift-dns.svc.cluster.local

  tunnels:
    tls:
      openShiftRoute:
        enabled: true
