---
hostname: <id>.ggbridge.gitguardian.com

tls:
  enabled: true
  existingSecret: ggbridge-client-crt
  existingSecretKeys:
    caCrt: ca.crt
    crt: tls.crt
    key: tls.key

client:
  tunnels:
    tls:
      enabled: true

proxy:
  tunnels:
    tls:
      service:
        type: LoadBalancer
        ports:
          tls:
            # 443 is the default TLS port
            port: 443
