---
hostname: <id>.ggbridge.gitguardian.com

tls:
  enabled: true
  existingSecret: ggbridge-client-crt
  existingSecretKeys:
    caCrt: ca.crt
    crt: tls.crt
    key: tls.key

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: false

client:
  tunnels:
    web:
      enabled: true

proxy:
  resolver: dns-default.openshift-dns.svc.cluster.local

  tunnels:
    web:
      openShiftRoute::
        enabled: true
        listeners:
          - hostname: hook-gitguardian.internal.com
            backend: hook.gitguardian.com
            tls:
              termination: edge
