{{- if and (eq .Values.mode "client") .Values.pdb.create }}
  {{- range $index := until (.Values.deploymentCount | int) }}
    {{- $fullname := include "ggbridge.fullname" $ }}
    {{- $clientFullname := include "ggbridge.client.fullname" $ }}
    {{- $indexClientFullname := printf "%s-%d" $clientFullname ($index | int) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $indexClientFullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.client.labels" $ | nindent 4 }}
    index: {{ $index | quote }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "ggbridge.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.pdb.minAvailable }}
  minAvailable: {{ $.Values.pdb.minAvailable }}
  {{- end  }}
  {{- if or $.Values.pdb.maxUnavailable ( not $.Values.pdb.minAvailable ) }}
  maxUnavailable: {{ $.Values.pdb.maxUnavailable | default 1 }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "ggbridge.selectorLabels" $ | nindent 6 }}
      {{- include "ggbridge.client.selectorLabels" $ | nindent 6 }}
      index: {{ $index | quote }}
  {{- end }}
{{- end }}
