{{- if and (eq .Values.mode "client") (eq (include "ggbridge.proxy.enabled" .) "true") -}}
  {{- $clientFullname := include "ggbridge.client.fullname" $ }}
  {{- range $index := until (.Values.deploymentCount | int) }}
    {{- $indexClientFullname := printf "%s-%d" $clientFullname ($index | int) }}
    {{- $indexClientProxyFullname := printf "%s-proxy-%d" $clientFullname ($index | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $indexClientProxyFullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ggbridge.labels" $ | nindent 4 }}
    {{- include "ggbridge.client.labels" $ | nindent 4 }}
    index: {{ $index | quote }}
  {{- if or $.Values.commonAnnotations $.Values.proxy.service.annotations }}
  {{- $annotations := include "ggbridge.tplvalues.merge" ( dict "values" ( list $.Values.proxy.service.annotations $.Values.commonAnnotations ) "context" $ ) }}
  annotations: {{- include "ggbridge.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    {{- range $key, $value := $.Values.client.tunnels }}
      {{- if $value.enabled }}
        {{- $port := get $.Values.proxy.service.ports $key }}
    - port: {{ $port.port }}
      targetPort: {{ $key }}
        {{- with $port.nodePort }}
      nodePort: {{ . }}
        {{- end }}
      protocol: TCP
      name: {{ $key }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "ggbridge.selectorLabels" $ | nindent 4 }}
    {{- include "ggbridge.client.selectorLabels" $ | nindent 4 }}
    index: {{ $index | quote }}
  {{- end }}
{{- end }}
