networks:
  public:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "${PUBLIC_NETWORK_GATEWAY}"
    ipam:
      config:
        - subnet: ${PUBLIC_NETWORK_SUBNET}
          gateway: ${PUBLIC_NETWORK_GATEWAY}

  gitguardian:
    driver: bridge

  client:
    driver: bridge

services:

### GitGuadian network
#######################################

  # GitGuardian Internal Monitoring (GIM)
  gitguardian:
    image: ${GGBRIDGE_IMAGE}
    entrypoint:
      - /usr/sbin/nginx
    command:
      - -c
      - /etc/nginx/nginx.conf
      - -g
      - daemon off;
    environment:
      CURL_CA_BUNDLE: "/certs/ca.crt"
    volumes:
      - ./certs:/certs
      - ./files/gitguardian/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - name: gitguardian
        target: 443
        host_ip: ${PUBLIC_NETWORK_GATEWAY}
        published: 443
        app_protocol: http
        mode: host
    networks:
      gitguardian:
      public:
        aliases:
          # GIM public API endpoint (used by ggshield)
          - api.gitguardian.public
          # GIM dashboard endpoint
          - dashboard.gitguardian.public
          # GIM incoming webhooks endpoint
          - hook.gitguardian.public

  # ggbridge server
  server:
    image: ${GGBRIDGE_IMAGE}
    entrypoint: ggbridge
    command: server
    environment:
      SERVER_LISTEN: "0.0.0.0"
      TLS_ENABLED: "true"
      LOG_LEVEL: ${LOG_LEVEL}
      CURL_CA_BUNDLE: "/certs/ca.crt"
    volumes:
      - ./certs:/certs
      - ./files/server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      gitguardian:
        aliases:
          - proxy.gitguardian.internal
      public:
        aliases:
          # GitGuardian tunnel endpoint
          - tunnel.gitguardian.public
    extra_hosts:
      kube-dns.kube-system.svc.cluster.local: "127.0.0.11"

### Client network
#######################################

  # ggbridge client
  client:
    image: ${GGBRIDGE_IMAGE}
    entrypoint: ggbridge
    command: client
    deploy:
      replicas: 1
    environment:
      SERVER_ADDRESS: "tunnel.gitguardian.public"
      TLS_ENABLED: "true"
      LOG_LEVEL: ${LOG_LEVEL}
      CLIENT_TUNNEL_TLS_ENABLED: "true"
    volumes:
       - ./certs:/certs
    networks:
      client:
        aliases:
          - api.gitguardian.public
          - dashboard.gitguardian.public
          - hook.gitguardian.public
          - forbidden.gitguardian.public
      public:
    extra_hosts:
      kube-dns.kube-system.svc.cluster.local: "127.0.0.11"
    depends_on:
      - server

  # Version Control System server
  vcs:
    image: ${GGBRIDGE_IMAGE}
    entrypoint:
      - /usr/sbin/nginx
    command:
      - -c
      - /etc/nginx/nginx.conf
      - -g
      - daemon off;
    environment:
      CURL_CA_BUNDLE: "/certs/ca.crt"
    volumes:
      - ./certs:/certs
      - ./files/vcs/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      client:
        aliases:
          - vcs.client.internal

  # Developer host
  developer:
    image: ${GGBRIDGE_IMAGE}
    entrypoint: []
    command:
      - sleep
      - infinity
    environment:
      CURL_CA_BUNDLE: "/certs/ca.crt"
    volumes:
      - ./certs:/certs
    networks:
      - client
    extra_hosts:
      # GIM public API endpoint (used by ggshield)
      api.gitguardian.public: "${PUBLIC_NETWORK_GATEWAY}"
      # GIM dashboard endpoint
      dashboard.gitguardian.public: "${PUBLIC_NETWORK_GATEWAY}"
