name: Sign and Attest Docker images
description: 'Sign  and Attest Docker images using Cosign'

inputs:
  image:
    description: 'The image repository'
    required: true
  tag:
    description: 'The image tag'
    required: true
  sbom-path:
    description: 'The SBOM directory'
    required: false
    default: ${{ runner.temp }}/sbom
  attest-sbom:
    description: 'Attest SBOMs'
    required: false
    default: 'true'
  attest-provenance:
    description: 'Attest the build provenance'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: imjasonh/setup-crane@v0.4
    - uses: sigstore/cosign-installer@v3

    - id: digest
      shell: bash
      run: |
        echo "digest=$(crane digest ghcr.io/${{ inputs.image }}:${{ inputs.tag }})" >> $GITHUB_OUTPUT
        echo "digest-amd64=$(crane digest ghcr.io/${{ inputs.image }}:${{ inputs.tag }} --platform=linux/amd64)" >> $GITHUB_OUTPUT
        echo "digest-arm64=$(crane digest ghcr.io/${{ inputs.image }}:${{ inputs.tag }} --platform=linux/arm64)" >> $GITHUB_OUTPUT

    - id: sign
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign sign \
          --recursive \
          --oidc-provider=github-actions \
          ghcr.io/${{ inputs.image }}@${{ steps.digest.outputs.digest }}
        cosign sign \
          --recursive \
          --oidc-provider=github-actions \
          docker.io/${{ inputs.image }}@${{ steps.digest.outputs.digest }}

    - if: ${{ inputs.attest-sbom == 'true' }}
      id: attest-sbom-index
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-index.spdx.json \
          --oidc-provider=github-actions \
          ghcr.io/${{ inputs.image }}@${{ steps.digest.outputs.digest }}
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-index.spdx.json \
          --oidc-provider=github-actions \
          docker.io/${{ inputs.image }}@${{ steps.digest.outputs.digest }}

    - if: ${{ inputs.attest-sbom == 'true' }}
      id: attest-sbom-amd64
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-x86_64.spdx.json \
          --oidc-provider=github-actions \
          ghcr.io/${{ inputs.image }}@${{ steps.digest.outputs.digest-amd64 }}
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-x86_64.spdx.json \
          --oidc-provider=github-actions \
          docker.io/${{ inputs.image }}@${{ steps.digest.outputs.digest-amd64 }}

    - if: ${{ inputs.attest-sbom == 'true' }}
      id: attest-sbom-arm64
      shell: bash
      env:
        COSIGN_YES: "true"
      run: |
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-aarch64.spdx.json \
          --oidc-provider=github-actions \
          ghcr.io/${{ inputs.image }}@${{ steps.digest.outputs.digest-arm64 }}
        cosign attest \
          --type=spdxjson \
          --predicate=${{ inputs.sbom-path }}/sbom-aarch64.spdx.json \
          --oidc-provider=github-actions \
          docker.io/${{ inputs.image }}@${{ steps.digest.outputs.digest-arm64 }}

    - if: ${{ inputs.attest-provenance == 'true' }}
      id: attest-provenance-github
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ inputs.image }}
        subject-digest: ${{ steps.digest.outputs.digest }}
        push-to-registry: true
