name: Scan Image
description: 'Scan Image using Grype'

inputs:
  image:
    description: 'The image to scan'
    required: true
  fail-build:
    description: "Set to false to avoid failing based on severity-cutoff. Default is to fail when severity-cutoff is reached (or surpassed)"
    required: false
    default: 'true'
  severity-cutoff:
    description: 'Optionally specify the minimum vulnerability severity to trigger an "error" level ACS result.  Valid choices are "negligible", "low", "medium", "high" and "critical".  Any vulnerability with a severity less than this value will lead to a "warning" result.  Default is "high".'
    required: false
    default: 'high'
  upload:
    description: 'Whether to upload report file or not'
    required: false
    default: 'false'

outputs:
  report:
    description: 'Scan report file'
    value: ${{ steps.scan.outputs.sarif }}

runs:
  using: composite
  steps:
    - name: Scan image
      id: scan
      uses: anchore/scan-action@v6
      with:
        image: ${{ inputs.image }}
        cache-db: true
        fail-build: ${{ inputs.fail-build }}
        severity-cutoff: ${{ inputs.severity-cutoff }}
        output-format: 'sarif'

    - if: ${{ inputs.upload == 'true' }}
      name: Upload scan report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
