name: ggbridge

services:

  client:
    image: gitguardian/ggbridge:latest-shell
    environment:
      SERVER_ADDRESS: <subdomain>.ggbridge.gitguardian.com
      TLS_ENABLED: "true"
      LOG_LEVEL: INFO
    volumes:
      - ./certs/ca.crt:/etc/ggbridge/tls/ca.crt:ro
      - ./certs/client.crt:/etc/ggbridge/tls/client.crt:ro
      - ./certs/client.key:/etc/ggbridge/tls/client.key:ro
    restart: on-failure
    extra_hosts:
      kube-dns.kube-system.svc.cluster.local: "127.0.0.11"
