name: ggbridge

services:

  client:
    image: gitguardian/ggbridge
    environment:
      SERVER_ADDRESS: <subdomain>.ggbridge.gitguardian.com
      TLS_ENABLED: "true"
      LOG_LEVEL: INFO
    volumes:
      - ./certs/client.crt:/etc/ggbridge/tls/client.crt:ro
      - ./certs/client.key:/etc/ggbridge/tls/client.key:ro
    restart: on-failure
