name: ggbridge

services:

  server:
    image: gitguardian/ggbridge:unstable-debug
    entrypoint:
      - ggbridge
    command:
      - server
    environment:
      TLS_ENABLED: "true"
      LOG_LEVEL: INFO
    volumes:
      - ./certs/ca.crt:/etc/ggbridge/tls/ca.crt:ro
      - ./certs/server.crt:/etc/ggbridge/tls/server.crt:ro
      - ./certs/server.key:/etc/ggbridge/tls/server.key:ro
    restart: on-failure
