on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  call-org-workflow:
    uses: GitGuardian/.github/.github/workflows/ggscout.yml@main
    with:
      param: value
    secrets: inherit
