name: Helm Release

on:
  push:
    tags:
      - 'helm/chart/v*'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  DAGGER_VERSION: "0.15.1"
  GH_DOCKER_REPOSITORY: ${{ vars.GH_DOCKER_REPOSITORY }}
  GH_HELM_REPOSITORY: ${{ vars.GH_HELM_REPOSITORY }}

jobs:
  helm:
    name: Push Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set release version
        id: version
        run: |
          # Extract the tag, remove "v" prefix if it exists
          RAW_VERSION=${GITHUB_REF##*/}
          VERSION=${RAW_VERSION#v}
          echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Lint
        uses: dagger/dagger-for-github@v7.0.3
        with:
          version: ${{ env.DAGGER_VERSION }}
          engine-stop: false
          module: github.com/opopops/daggerverse/helm@v1.2.1
          verb: call
          args: |
            lint \
              --path=helm/ggbridge \
              --strict \

      - name: Publish Helm chart
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GH_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ env.DAGGER_VERSION }}
          module: github.com/opopops/daggerverse/helm@v1.2.1
          verb: call
          args: |
            package-push \
              --path=helm/ggbridge \
              --version="${{ env.RELEASE_VERSION }}" \
              --app-version="${{ env.RELEASE_VERSION }}" \
              --registry=ghcr.io/${GH_HELM_REPOSITORY} \
              --username=${{ github.actor }} \
              --password=env:GH_REGISTRY_PASSWORD \
